# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prototype.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/lock_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 450))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/whitecat.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_selectBrowser = QtWidgets.QLabel(self.centralwidget)
        self.label_selectBrowser.setGeometry(QtCore.QRect(91, 659, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_selectBrowser.setFont(font)
        self.label_selectBrowser.setAutoFillBackground(True)
        self.label_selectBrowser.setObjectName("label_selectBrowser")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(81, 704, 651, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chromeButton = QtWidgets.QPushButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/Google-Chrome-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chromeButton.setIcon(icon1)
        self.chromeButton.setIconSize(QtCore.QSize(20, 20))
        self.chromeButton.setObjectName("chromeButton")
        self.horizontalLayout.addWidget(self.chromeButton)
        self.FireFoxButton = QtWidgets.QPushButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/Firefox-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FireFoxButton.setIcon(icon2)
        self.FireFoxButton.setIconSize(QtCore.QSize(20, 20))
        self.FireFoxButton.setObjectName("FireFoxButton")
        self.horizontalLayout.addWidget(self.FireFoxButton)
        self.OperaButton = QtWidgets.QPushButton(self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/Opera-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OperaButton.setIcon(icon3)
        self.OperaButton.setIconSize(QtCore.QSize(20, 20))
        self.OperaButton.setObjectName("OperaButton")
        self.horizontalLayout.addWidget(self.OperaButton)
        self.MicrosoftEdge = QtWidgets.QPushButton(self.layoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/icons8-microsoft-edge-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MicrosoftEdge.setIcon(icon4)
        self.MicrosoftEdge.setIconSize(QtCore.QSize(20, 20))
        self.MicrosoftEdge.setObjectName("MicrosoftEdge")
        self.horizontalLayout.addWidget(self.MicrosoftEdge)
        self.label_noOfWords = QtWidgets.QLabel(self.centralwidget)
        self.label_noOfWords.setGeometry(QtCore.QRect(90, 860, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_noOfWords.setFont(font)
        self.label_noOfWords.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_noOfWords.setObjectName("label_noOfWords")
        self.comboBox_Number_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Number_2.setEnabled(True)
        self.comboBox_Number_2.setGeometry(QtCore.QRect(90, 920, 81, 31))
        self.comboBox_Number_2.setObjectName("comboBox_Number_2")
        self.comboBox_Number_2.addItem("")
        self.comboBox_Number_2.addItem("")
        self.comboBox_Number_2.addItem("")
        self.comboBox_Number_2.addItem("")
        self.comboBox_Number_2.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(150, 380, 591, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(90, 770, 501, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_Alphabet = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_Alphabet.setEnabled(True)
        self.checkBox_Alphabet.setCheckable(True)
        self.checkBox_Alphabet.setObjectName("checkBox_Alphabet")
        self.horizontalLayout_2.addWidget(self.checkBox_Alphabet)
        self.checkBox_Number = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_Number.setEnabled(True)
        self.checkBox_Number.setCheckable(True)
        self.checkBox_Number.setObjectName("checkBox_Number")
        self.horizontalLayout_2.addWidget(self.checkBox_Number)
        self.checkBox_Symbol = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_Symbol.setEnabled(True)
        self.checkBox_Symbol.setCheckable(True)
        self.checkBox_Symbol.setObjectName("checkBox_Symbol")
        self.horizontalLayout_2.addWidget(self.checkBox_Symbol)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_Alphabet = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_Alphabet.setEnabled(False)
        self.comboBox_Alphabet.setObjectName("comboBox_Alphabet")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.comboBox_Alphabet.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_Alphabet)
        self.comboBox_Number = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_Number.setEnabled(False)
        self.comboBox_Number.setObjectName("comboBox_Number")
        self.comboBox_Number.addItem("")
        self.comboBox_Number.addItem("")
        self.comboBox_Number.addItem("")
        self.comboBox_Number.addItem("")
        self.comboBox_Number.addItem("")
        self.comboBox_Number.addItem("")
        self.comboBox_Number.addItem("")
        self.comboBox_Number.addItem("")
        self.comboBox_Number.addItem("")
        self.comboBox_Number.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_Number)
        self.comboBox_Symbol = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_Symbol.setEnabled(False)
        self.comboBox_Symbol.setObjectName("comboBox_Symbol")
        self.comboBox_Symbol.addItem("")
        self.comboBox_Symbol.addItem("")
        self.comboBox_Symbol.addItem("")
        self.comboBox_Symbol.addItem("")
        self.comboBox_Symbol.addItem("")
        self.comboBox_Symbol.addItem("")
        self.comboBox_Symbol.addItem("")
        self.comboBox_Symbol.addItem("")
        self.comboBox_Symbol.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_Symbol)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.genPwd = QtWidgets.QPushButton(self.centralwidget)
        self.genPwd.setEnabled(True)
        self.genPwd.setGeometry(QtCore.QRect(370, 900, 141, 51))
        self.genPwd.setAutoFillBackground(False)
        self.genPwd.setStyleSheet("")
        self.genPwd.setCheckable(False)
        self.genPwd.setChecked(False)
        self.genPwd.setFlat(False)
        self.genPwd.setObjectName("genPwd")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EzPass"))
        self.label_selectBrowser.setText(_translate("MainWindow", "Select Your Browser"))
        self.chromeButton.setText(_translate("MainWindow", "Google Chrome"))
        self.FireFoxButton.setText(_translate("MainWindow", "FireFox"))
        self.OperaButton.setText(_translate("MainWindow", "Opera"))
        self.MicrosoftEdge.setText(_translate("MainWindow", "Microsoft Edge"))
        self.label_noOfWords.setText(_translate("MainWindow", "Select number of words"))
        self.comboBox_Number_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_Number_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_Number_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_Number_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_Number_2.setItemText(4, _translate("MainWindow", "5"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">Guide: How to generate a password</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt;\"><br /></p></body></html>"))
        self.checkBox_Alphabet.setText(_translate("MainWindow", "Alphabet"))
        self.checkBox_Number.setText(_translate("MainWindow", "Number"))
        self.checkBox_Symbol.setText(_translate("MainWindow", "Symbol"))
        self.comboBox_Alphabet.setItemText(0, _translate("MainWindow", "A"))
        self.comboBox_Alphabet.setItemText(1, _translate("MainWindow", "B"))
        self.comboBox_Alphabet.setItemText(2, _translate("MainWindow", "C"))
        self.comboBox_Alphabet.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_Alphabet.setItemText(4, _translate("MainWindow", "E"))
        self.comboBox_Alphabet.setItemText(5, _translate("MainWindow", "F"))
        self.comboBox_Alphabet.setItemText(6, _translate("MainWindow", "G"))
        self.comboBox_Alphabet.setItemText(7, _translate("MainWindow", "H"))
        self.comboBox_Alphabet.setItemText(8, _translate("MainWindow", "I"))
        self.comboBox_Alphabet.setItemText(9, _translate("MainWindow", "J"))
        self.comboBox_Alphabet.setItemText(10, _translate("MainWindow", "K"))
        self.comboBox_Alphabet.setItemText(11, _translate("MainWindow", "L"))
        self.comboBox_Alphabet.setItemText(12, _translate("MainWindow", "M"))
        self.comboBox_Alphabet.setItemText(13, _translate("MainWindow", "N"))
        self.comboBox_Alphabet.setItemText(14, _translate("MainWindow", "O"))
        self.comboBox_Alphabet.setItemText(15, _translate("MainWindow", "P"))
        self.comboBox_Alphabet.setItemText(16, _translate("MainWindow", "Q"))
        self.comboBox_Alphabet.setItemText(17, _translate("MainWindow", "R"))
        self.comboBox_Alphabet.setItemText(18, _translate("MainWindow", "S"))
        self.comboBox_Alphabet.setItemText(19, _translate("MainWindow", "T"))
        self.comboBox_Alphabet.setItemText(20, _translate("MainWindow", "U"))
        self.comboBox_Alphabet.setItemText(21, _translate("MainWindow", "V"))
        self.comboBox_Alphabet.setItemText(22, _translate("MainWindow", "W"))
        self.comboBox_Alphabet.setItemText(23, _translate("MainWindow", "X"))
        self.comboBox_Alphabet.setItemText(24, _translate("MainWindow", "Y"))
        self.comboBox_Alphabet.setItemText(25, _translate("MainWindow", "Z"))
        self.comboBox_Number.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_Number.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_Number.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_Number.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_Number.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_Number.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_Number.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_Number.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_Number.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_Number.setItemText(9, _translate("MainWindow", "0"))
        self.comboBox_Symbol.setItemText(0, _translate("MainWindow", "!"))
        self.comboBox_Symbol.setItemText(1, _translate("MainWindow", "@"))
        self.comboBox_Symbol.setItemText(2, _translate("MainWindow", "#"))
        self.comboBox_Symbol.setItemText(3, _translate("MainWindow", "$"))
        self.comboBox_Symbol.setItemText(4, _translate("MainWindow", "%"))
        self.comboBox_Symbol.setItemText(5, _translate("MainWindow", "^"))
        self.comboBox_Symbol.setItemText(6, _translate("MainWindow", "&"))
        self.comboBox_Symbol.setItemText(7, _translate("MainWindow", "*"))
        self.comboBox_Symbol.setItemText(8, _translate("MainWindow", "?"))
        self.genPwd.setText(_translate("MainWindow", "Generate Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
