self.page_vault = QtWidgets.QWidget()
        self.page_vault.setObjectName("page_vault")
        self.groupBox_vault = QtWidgets.QGroupBox(self.page_vault)
        self.groupBox_vault.setGeometry(QtCore.QRect(round((self.stackedWidget.width() - 1300) / 2), round((self.stackedWidget.height() - 450 ) / 7 *6), 1300, 450))
        self.groupBox_vault.setObjectName("groupBox_vault")
        self.groupBox_vault.setProperty("class", "QGroupBox_genPas")
        self.verticalLayout_vault = QtWidgets.QVBoxLayout(self.groupBox_vault)
        self.verticalLayout_vault.setObjectName("verticalLayout_vault")
        self.container_1_vault = QtWidgets.QWidget()
        self.container_1_vault.setProperty("class", "containers_genPas")
        self.gridLayout_vault = QtWidgets.QGridLayout(self.container_1_vault)
        self.gridLayout_vault.setContentsMargins(25, 10, 15, 10)
        self.gridLayout_vault.setHorizontalSpacing(30)
        self.gridLayout_vault.setVerticalSpacing(10)
        self.gridLayout_vault.setObjectName("gridLayout_vault")
        self.label_Title_vault = QtWidgets.QLabel(self.page_vault)
        self.label_Title_vault.setProperty("class", "label_Title_genPas")
        self.label_Title_vault.setGeometry(QtCore.QRect(self.groupBox_vault.x() + 20, self.groupBox_vault.y() - 70, 300, 70))

        self.logoBackground_vault = QtWidgets.QLabel(self.page_vault)
        self.logoBackground_vault.setGeometry(QtCore.QRect(0, 0, self.stackedWidget.width(), 250))
        self.logoBackground_vault.setProperty("class", "logoBackground_genPas")
        self.label_vault = QtWidgets.QLabel(self.centralwidget)
        self.label_vault.setGeometry(QtCore.QRect( round((self.stackedWidget.width() - 560) / 2 ), 30, 560, 150))
        self.label_vault.setPixmap(QtGui.QPixmap("../images/ezPassLogo.PNG"))
        self.label_vault.setScaledContents(True)
        self.label_vault.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vault.setObjectName("label_vault")
        self.label_vault.setProperty("class", "label_logo")

        self.layoutWidget_1_vault = QtWidgets.QWidget(self.page_vault)
        self.layoutWidget_1_vault.setGeometry(QtCore.QRect(0, self.logoBackground_vault.height() - 30, self.stackedWidget.width(), 100)) 
        self.layoutWidget_1_vault.setProperty("class", "navBar_genPas")

        self.HomeBtn_vault = QtWidgets.QPushButton(self.layoutWidget_1_vault)
        self.HomeBtn_vault.setProperty("class", "navBar_btn")
        self.HomeBtn_vault.clicked.connect(self.homePg)
        self.SettingsBtn_vault = QtWidgets.QPushButton(self.layoutWidget_1_vault)
        self.SettingsBtn_vault.setProperty("class", "navBar_btn")
        self.AboutUsBtn_vault = QtWidgets.QPushButton(self.layoutWidget_1_vault)
        self.AboutUsBtn_vault.setProperty("class", "navBar_btn")
        self.dummyLabel_3_vault = QtWidgets.QLabel(self.layoutWidget_1_vault)
        self.dummyLabel_3_vault.setProperty("class", "QLabel_genPas")
        self.dummyLabel_4_vault = QtWidgets.QLabel(self.layoutWidget_1_vault)
        self.dummyLabel_4_vault.setProperty("class", "QLabel_genPas")

        self.navBar_vault = QtWidgets.QHBoxLayout(self.layoutWidget_1_vault)
        self.navBar_vault.addWidget(self.HomeBtn_vault)
        self.navBar_vault.addWidget(self.SettingsBtn_vault)
        self.navBar_vault.addWidget(self.AboutUsBtn_vault)
        self.navBar_vault.addWidget(self.dummyLabel_3_vault)
        self.navBar_vault.addWidget(self.dummyLabel_4_vault)

        self.stackedWidget.addWidget(self.page_vault)